### ISSUE TITLE
Embed内だと文字化けする

### ISSUE THREAD

**Issue by sevenc-nanashi** [CyberRex0/500choyen-api#2]
![EB67F235-C192-4991-BC04-217020A8B726](https://user-images.githubusercontent.com/59691627/112743657-2619dd00-8fd4-11eb-948a-635587fdf8f4.jpeg)

**Comment by sevenc-nanashi** [comment]
![309DD529-EDD4-4435-8C18-F2911F0F3E3D](https://user-images.githubusercontent.com/59691627/112743719-a6404280-8fd4-11eb-9883-158de4be6ec4.png)

描画のエンコーディングの問題…？

**Comment by CyberRex0** [comment]
URIエンコード(pythonであれば`urllib.parse.quote()`など)を使用すれば問題ありません。
