### ISSUE TITLE
エラー時のhttpステータスコードについて

### ISSUE THREAD

**Issue by nerrog** [CyberRex0/500choyen-api#8]
例えばパラメーター不足時に返される「パラメータbottomが不足しています。」等のエラーメッセージのページのステータスコードが通常の200 OKになっています
エラーページでは400 Bad Request等のステータスコードを返すようにしてみてはどうですか？

**Comment by CyberRex0** [comment]
修正しました。
https://github.com/CyberRex0/5000choyen-api/commit/efab6504c8eaea5b3fbe4f74e068c005f922c80d
